### ISSUE TITLE
release tarball

### ISSUE THREAD

**Issue by shibumi** [chr4/sslsecure.vim#2]
Hello,
could you please provide a release tarball via github? I would like to package this for the Arch Linux User Repository, thanks!

**Comment by chr4** [comment]
Glad to release a tarball, I've just tagged version `v1.0.0`.
I'd be glad seeing this in AUR! Thanks :)

If you want (and find it useful), you can also have a look at [nginx.vim](https://github.com/chr4/nginx.vim).

Once published, feel free to paste the link into this issue for future users!

**Comment by chr4** [comment]
I've added a reference to the README. Thanks for packaging!
