### ISSUE TITLE
SHA in HMAC

### ISSUE THREAD

**Issue by 2001db8** [chr4/sslsecure.vim#4]
Hi,

judging from the screenshots the pluing hightlights every occurrence of "SHA" even when it only indicates, that SHA-1 is used within the HMAC (https://en.wikipedia.org/wiki/Hash-based_message_authentication_code). 
Although SHA-1 is generally considered to be insecure these days (SHAttered and so on), SHA-1 as a hash fuction in a MAC/PRF is, as far as I know, still usable and not prone to collision attacks. So just highlighting every "SHA" might cause confusion and in the worst case even limit TLS capabilities if someone tries to get rid of everything-SHA-1 from his configs and ends up with cipher suites, which are only compatibe to a very limited set of clients.

Regards

Jens

**Comment by chr4** [comment]
Ah, good catch. I guess this is true and should be handeled. 
According to [Appendix C](https://tools.ietf.org/html/rfc5246#appendix-C), it seems like this would always be the case when SHA is the last element of a cipher string.

Can you comment on whether this is also the case for other ciphers (e.g. MD5) as a HMAC?

**Comment by 2001db8** [comment]
At least I can't think of any exception to this right now. Since most configurations use the OpenSSL notation to define cipher suites instead of the IETF way you should also refer to the [`openssl ciphers` Man-Page](https://www.openssl.org/docs/man1.1.0/apps/ciphers.html) since it lists all supported suites in both notations.

Theoretically and to my knowledge this ist also the case for MD5, yes. But I think under normal circumstances (no SSLv3, no RC4, no eNULL/aNULL) there should not be any cipher suites left using MD5 in their MAC.

**Comment by AlainG80** [comment]
MD5 in a HMAC or PRF is not a FIPS 140-4 approved cipher.

Try:
`openssl ciphers -v 'ALL:!ADH:@STRENGTH'`

**Comment by chr4** [comment]
What about this one?

```
$  openssl ciphers -v 'ALL:!ADH:@STRENGTH' |grep MD5
RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5
```

I just realized that SHA is always used only as a HMAC, never as anything else. If the assumtion from OP is true, then the checks for SHA could be removed in general, unless I'm missing something?

**Comment by chr4** [comment]
I've removed SHA highlighting completely from [nginx.vim](https://github.com/chr4/nginx.vim) and [sslsecure.vim](https://github.com/chr4/sslsecure.vim), as of my research with a few OpenSSL/ LibreSSL versions, they're only used as HMAC in all available cipher suites and should therefore be still considered safe.

Thanks @2001db8 for reporting!

**Comment by AlainG80** [comment]
> What about this one?
> 
> $  openssl ciphers -v 'ALL:!ADH:@STRENGTH' |grep MD5
> RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5

SSLv3 RFC 7568 should not be used anymore, neither is RC4 see RFC 7465

**Comment by 2001db8** [comment]
You are right, but this only means that `RC4-MD4` is a cipher specific to SSLv3. It does not mean that SSLv3 as a protocol will be negotiated. E.g. having `!SSLv3` in your cipher definitions will only delete SSLv3 ciphers from the list but not disable SSLv3 protocol.

**Comment by chr4** [comment]
Thanks for all the information! 

The purpose of this plugin is to highlight insecure cipher suites, and this issue was about potential false-positives with negative consequences (noteworthy compatibility issues).

From the discussion I conclude that highlighting RC4-MD5 doesn't imply noteworthy issues.
